services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: yarn start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: yarn run dev

volumes:
  backend_node_modules:
  frontend_node_modules:
