FROM node:22-alpine

WORKDIR /app

COPY package.json yarn.lock ./

# Enable corepack and install dependencies
RUN corepack enable && \
    yarn install --frozen-lockfile && \
    yarn cache clean

# Remove unnecessary files
RUN rm -rf /tmp/* /var/cache/apk/* /root/.yarn

EXPOSE 3000

CMD ["yarn", "start:dev"]